micronaut:
  application:
    name: dancingManager
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dancingdb
    username: postres
    password: mysecretpassword
